add_chore:
  name: Add Chore
  description: Add a new chore to track
  fields:
    name:
      name: Name
      description: The name of the chore
      required: true
      selector:
        text:
    due_date:
      name: Due Date
      description: The date when the chore is due
      required: true
      selector:
        date:
    interval:
      name: Interval (Days)
      description: How many days between recurring instances of this chore
      required: true
      selector:
        number:
          min: 1
          max: 365
          step: 1
    assigned_to:
      name: Assigned To
      description: Person assigned to the chore (optional)
      required: false
      selector:
        text:

remove_chore:
  name: Remove Chore
  description: Remove a chore from tracking
  fields:
    name:
      name: Name
      description: The name of the chore to remove
      required: true
      selector:
        entity:
          domain: sensor
          integration: chore_assistant

complete_chore:
  name: Complete Chore
  description: Mark a chore as completed
  fields:
    name:
      name: Name
      description: The name of the chore to complete
      required: true
      selector:
        entity:
          domain: sensor
          integration: chore_assistant

reset_chore:
  name: Reset Chore
  description: Reset a chore to pending state
  fields:
    name:
      name: Name
      description: The name of the chore to reset
      required: true
      selector:
        entity:
          domain: sensor
          integration: chore_assistant

list_chores:
  name: List Chores
  description: List all chores

check_recurring:
  name: Check Recurring Chores
  description: Manually check for recurring chores that need to be reset to pending
